// Builds 1920x1080 video slides for a course module from the course content itself (src/content/curso.ts):
// same slides as the lesson player (slidesFor), with big type for YouTube and the bottom-right corner left free
// for the avatar. Writes media/video-curso/<slug>/carrusel.html; render it with npm run carrusel -- video-curso/<slug>.
// Usage: node media/video-curso/generar.mjs modulo-0
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const { modules, slidesFor } = await import("../../src/content/curso.ts");
const slug = process.argv[2];
const mod = modules.find((m) => m.slug === slug);
if (!mod) {
  console.error(`Usage: node media/video-curso/generar.mjs <slug>  (${modules.map((m) => m.slug).join(", ")})`);
  process.exit(1);
}
const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const brand = `<div class="brand"><svg class="ml" data-ml width="70"></svg><span class="wm">vibe<span>coding</span>coach</span><span class="mod">Módulo ${mod.number}</span></div>`;

const cards = slidesFor(mod).map((s) => {
  const eyebrow = s.eyebrow ? `<p class="eyebrow">${esc(s.eyebrow)}</p>` : "";
  if (s.kind === "cover") {
    return `<section class="card cover">${brand}<div class="body">${eyebrow}<h1>${esc(s.title)}</h1><p class="lead">${esc(s.text ?? "")}</p></div></section>`;
  }
  if (s.kind === "prompt") {
    return `<section class="card">${brand}<div class="body">${eyebrow}<h2>${esc(s.title)}</h2><pre class="prompt">${esc(s.prompt ?? "")}</pre></div></section>`;
  }
  const items = (s.items ?? []).map((i) => `<li>${esc(i)}</li>`).join("");
  const tip = s.text ? `<p class="tip">${esc(s.text)}</p>` : "";
  return `<section class="card">${brand}<div class="body">${eyebrow}<h2>${esc(s.title)}</h2><ul>${items}</ul>${tip}</div></section>`;
});

const html = `<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<title>Vídeo · Módulo ${mod.number}: ${esc(mod.title)}</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;600;700;800&display=block" rel="stylesheet">
<link href="../../kit/kit.css" rel="stylesheet">
<style>
  /* Generated by media/video-curso/generar.mjs: edit the course content, not this file. */
  body { display: grid; gap: 40px; justify-content: center; padding: 40px 0; background: #ddd; }
  .card { position: relative; width: 1920px; height: 1080px; overflow: hidden; background: url("../../../public/fondo-burbujas.webp") center / cover; font-family: Inter, system-ui, sans-serif; color: var(--ink); -webkit-font-smoothing: antialiased; }
  .card::after { position: absolute; inset: 0; background: radial-gradient(65% 75% at 35% 50%, rgba(250, 251, 253, 0.9), rgba(250, 251, 253, 0.2)); content: ""; }
  .card > * { position: relative; z-index: 1; }
  .brand { position: absolute; top: 56px; left: 110px; display: flex; align-items: center; gap: 16px; font-size: 32px; font-weight: 800; letter-spacing: -0.03em; }
  .brand .wm span { color: var(--orange); }
  .brand .mod { margin-left: 14px; border-radius: 999px; background: rgba(255, 112, 52, 0.12); color: var(--accent-ink); font-size: 24px; font-weight: 750; letter-spacing: 0; padding: 8px 18px; }
  /* Content stays left of the avatar bubble (bottom right, about 520px wide). */
  .body { position: absolute; top: 170px; bottom: 110px; left: 110px; width: 1180px; display: flex; flex-direction: column; justify-content: center; }
  .eyebrow { align-self: flex-start; margin: 0 0 26px; border: 2px solid rgba(255, 112, 52, 0.25); border-radius: 999px; background: rgba(255, 112, 52, 0.12); color: var(--accent-ink); font-size: 30px; font-weight: 750; padding: 10px 24px; }
  h1 { margin: 0; font-size: 118px; font-weight: 800; letter-spacing: -0.05em; line-height: 1; }
  h2 { margin: 0; font-size: 80px; font-weight: 800; letter-spacing: -0.045em; line-height: 1.04; }
  .lead { margin: 36px 0 0; color: var(--muted); font-size: 44px; font-weight: 500; line-height: 1.35; }
  ul { margin: 44px 0 0; padding: 0; list-style: none; }
  li { display: flex; gap: 24px; font-size: 44px; font-weight: 600; line-height: 1.3; }
  li + li { margin-top: 26px; }
  li::before { flex: none; width: 18px; height: 18px; margin-top: 20px; border-radius: 50%; background: var(--grad); content: ""; }
  .tip { margin: 44px 0 0; border-left: 8px solid var(--orange); border-radius: 8px; background: rgba(255, 255, 255, 0.7); color: var(--accent-ink); font-size: 38px; font-weight: 700; line-height: 1.35; padding: 22px 30px; }
  .prompt { margin: 44px 0 0; white-space: pre-wrap; border-radius: 30px; background: #1f1b26; box-shadow: inset 8px 0 0 var(--orange), 0 30px 60px rgba(31, 27, 38, 0.25); color: #f1edf7; font-family: "SFMono-Regular", Menlo, monospace; font-size: 38px; line-height: 1.5; padding: 40px 46px; }
</style>
</head>
<body>
${cards.join("\n")}
</body>
</html>
`;
const dir = join(dirname(fileURLToPath(import.meta.url)), slug);
mkdirSync(dir, { recursive: true });
writeFileSync(join(dir, "carrusel.html"), html);
console.log(`${cards.length} slides → ${join(dir, "carrusel.html")}`);
