/** Prompt library: the single source of every prompt on the site. Guides reference them by id
 * (a "prompt" block in recursos.ts) and /curso/prompts lists them all. [Brackets] mark the parts to fill in. */
export const promptCategories = [
  "Empezar",
  "Construir",
  "Arreglar y revisar",
  "Seguridad",
  "Diseño e imágenes",
  "Aprender",
  "Trabajar mejor",
  "Contenido y redes",
] as const;
export type PromptCategory = (typeof promptCategories)[number];

export type LibraryPrompt = {
  id: string;
  category: PromptCategory;
  title: string;
  /** When to use it, in one line. */
  when: string;
  text: string;
  /** Slug of the course guide that explains it in context. */
  guide?: string;
};

export const prompts: LibraryPrompt[] = [
  {
    id: "mi-ordenador",
    category: "Empezar",
    title: "¿Me sirve mi ordenador?",
    when: "Antes de comprar nada, para saber si tu ordenador sirve y qué instalar.",
    text: "Tengo este ordenador: [modelo, sistema operativo, RAM y disco]. Quiero aprender a crear webs con IA. ¿Me sirve? ¿Qué debería instalar y qué no? Dame los pasos para mi sistema.",
    guide: "que-necesitas",
  },
  {
    id: "proyecto-nuevo",
    category: "Empezar",
    title: "Primer mensaje para un proyecto nuevo",
    when: "El primer mensaje de cualquier proyecto: que te proponga un plan antes de programar.",
    text: "Quiero crear [qué] para [quién]. Nunca he programado. Antes de escribir código, propón un plan sencillo por pasos y espera a que te diga que sí.",
    guide: "claude-code-primer-dia",
  },
  {
    id: "elegir-herramienta",
    category: "Empezar",
    title: "¿Con qué herramienta empiezo?",
    when: "Cuando tienes una idea y no sabes qué IA usar para construirla.",
    text: "Quiero crear [qué quieres construir] y nunca he programado. Compara tres formas de hacerlo con IA (por ejemplo, Claude, Cursor o Kimi): ventajas, inconvenientes y coste de cada una. Después recomiéndame una para alguien de mi nivel y dime el primer paso.",
    guide: "que-necesitas",
  },
  {
    id: "conectar-ia-gratis",
    category: "Construir",
    title: "Añadir IA gratis a tu web",
    when: "Para añadir a tu web una función con IA usando una API gratuita.",
    text: "Añade a mi web un botón que resuma el texto del formulario usando la API de Groq. La clave está en la variable GROQ_API_KEY del archivo .env: léela desde ahí y no la escribas en el código. Explícame qué archivos vas a tocar antes de empezar.",
    guide: "ia-gratis",
  },
  {
    id: "landing-negocio",
    category: "Construir",
    title: "Página de inicio para un negocio",
    when: "Para la primera versión de la web de un negocio o un proyecto personal.",
    text: "Crea la página de inicio de [nombre del negocio], dirigida a [quién es su cliente]. Secciones: [por ejemplo: cabecera, servicios, opiniones, contacto]. Estilo: [colores y sensación que quieres transmitir]. Que se vea bien en el móvil. Explícame la estructura antes de escribir el código.",
    guide: "hablar-con-claude",
  },
  {
    id: "formulario-contacto",
    category: "Construir",
    title: "Formulario de contacto",
    when: "Cuando quieres que la gente te escriba desde tu web.",
    text: "Añade un formulario de contacto con nombre, email y mensaje. Comprueba que los campos están bien rellenados, muestra un mensaje de «gracias» al enviar y explícame dónde me llegarán los mensajes. Sin servicios de pago.",
  },
  {
    id: "guardar-datos",
    category: "Construir",
    title: "Guardar datos en una base de datos",
    when: "Cuando tu web tiene que recordar cosas: reservas, usuarios, pedidos.",
    text: "Quiero guardar [qué datos] en una base de datos de Supabase. Diseña la tabla, activa la seguridad por filas (RLS) para que cada usuario solo vea lo suyo y explícame cada paso antes de aplicarlo.",
    guide: "seguridad",
  },
  {
    id: "publicar",
    category: "Construir",
    title: "Publicar en internet",
    when: "Cuando tu proyecto funciona en tu ordenador y quieres un enlace para compartirlo.",
    text: "Ayúdame a publicar este proyecto en Vercel. Primero comprueba que compila sin errores, que las claves están en variables de entorno y no en el código, y después dime qué pasos tengo que hacer yo y cuáles puedes hacer tú.",
    guide: "despliegues-vercel",
  },
  {
    id: "revision-otra-ia",
    category: "Arreglar y revisar",
    title: "Que otra IA lo revise",
    when: "Para que una IA revise el trabajo de otra antes de darlo por bueno.",
    text: "Actúa como revisor exigente. Esto lo ha hecho otra IA para conseguir [objetivo]: [pega aquí el resultado]. Busca errores, cosas que se puedan simplificar y riesgos. Ordénalos de más a menos importante y no reescribas nada todavía.",
    guide: "segunda-opinion",
  },
  {
    id: "rescate",
    category: "Arreglar y revisar",
    title: "Rescate: cuando todo se ha liado",
    when: "Cuando la IA ha hecho muchos cambios y ya nada funciona.",
    text: "Para. No cambies nada más. Explícame en qué estado está el proyecto, qué has cambiado en los últimos pasos y cuál crees que es el problema. Después propón cómo volver a la última versión que funcionaba.",
    guide: "errores-tipicos",
  },
  {
    id: "explicar-error",
    category: "Arreglar y revisar",
    title: "Entender un error",
    when: "Cada vez que aparece un mensaje de error que no entiendes.",
    text: "Me aparece este error: [pega aquí el error completo]. Explícame en lenguaje sencillo qué significa y por qué ha pasado, y propón cómo arreglarlo. No cambies nada hasta que te diga que sí.",
    guide: "errores-tipicos",
  },
  {
    id: "se-ve-mal",
    category: "Arreglar y revisar",
    title: "Algo se ve mal",
    when: "Cuando el diseño no queda como esperabas. Adjunta una captura de pantalla.",
    text: "Te adjunto una captura. Lo que está mal: [describe qué ves]. Cómo debería verse: [describe lo que quieres]. Arréglalo sin tocar el resto del diseño.",
    guide: "truquillos",
  },
  {
    id: "revisar-movil",
    category: "Arreglar y revisar",
    title: "Revisión para móvil",
    when: "Antes de publicar: la mayoría de la gente verá tu web en el móvil.",
    text: "Revisa cómo se ve la web en un móvil de 360 píxeles de ancho: textos cortados, botones demasiado pequeños o cosas que se salen de la pantalla. Haz una lista y arréglalas de una en una.",
  },
  {
    id: "auditoria-seguridad",
    category: "Seguridad",
    title: "Auditoría de seguridad",
    when: "Antes de publicar una app con usuarios, datos o pagos.",
    text: "Revisa este proyecto como un experto en seguridad. Busca: claves expuestas en el código del navegador, tablas sin control de acceso, rutas del servidor que no comprueban quién hace la petición, datos que deberían calcularse en el servidor y llamadas a servicios de pago sin límite. Para cada problema dime dónde está, qué podría hacer un atacante y cómo arreglarlo. Ordénalos de más a menos grave y no cambies nada todavía.",
    guide: "seguridad",
  },
  {
    id: "revisar-claves",
    category: "Seguridad",
    title: "Busca claves expuestas",
    when: "Antes de subir un proyecto a GitHub o publicarlo.",
    text: "Busca en este proyecto claves, contraseñas o tokens escritos en el código o en archivos que se vayan a subir a GitHub. Dime dónde están y cómo moverlos al archivo .env, sin mostrarme su valor.",
    guide: "seguridad",
  },
  {
    id: "fondo-web",
    category: "Diseño e imágenes",
    title: "Fondo para tu web",
    when: "Para generar un fondo para tu web con cualquier IA de imágenes.",
    text: "Fondo abstracto para una web, estilo glassmorphism: formas de cristal translúcido y burbujas suaves, tonos melocotón y naranja coral sobre blanco cálido, iluminación suave. Centro despejado para poner texto encima. Sin texto, sin logos, sin personas. Formato vertical 9:16.",
    guide: "fondos-e-imagenes",
  },
  {
    id: "paleta-tipografia",
    category: "Diseño e imágenes",
    title: "Paleta de colores y tipografías",
    when: "Al empezar el diseño, para que tu web tenga personalidad.",
    text: "Propón tres paletas de colores y una combinación de tipografías para [tu negocio y el estilo que buscas]. Explica qué transmite cada opción y aplica la que yo elija.",
  },
  {
    id: "cartel-con-texto",
    category: "Diseño e imágenes",
    title: "Cartel o portada con texto",
    when: "Para imágenes que llevan texto (carteles, portadas, miniaturas). Va mejor en Ideogram.",
    text: "Cartel vertical para [qué anuncias], estilo [moderno / minimalista / acuarela…], colores [tus colores]. Texto principal, escrito exactamente así: «[tu texto]». Fondo limpio, sin logos ni marcas.",
    guide: "herramientas-creativas",
  },
  {
    id: "clip-de-video",
    category: "Diseño e imágenes",
    title: "Clip de vídeo para redes",
    when: "Para generar un vídeo corto con Kling, Flow o similares. El texto ponlo tú después.",
    text: "Vídeo vertical 9:16 de 5 segundos: [qué pasa en la escena], [lugar y luz], cámara que [se acerca despacio / gira alrededor]. Estilo realista y luminoso. Sin texto, sin logos y sin personas reconocibles.",
    guide: "herramientas-creativas",
  },
  {
    id: "profesor-particular",
    category: "Aprender",
    title: "Profesor particular",
    when: "Cuando quieres aprender de verdad, no que te lo hagan.",
    text: "A partir de ahora actúa como mi profesor. Soy principiante. Cuando te pregunte algo, explícamelo con un ejemplo sencillo, comprueba con una pregunta que lo he entendido y no avances hasta que responda.",
    guide: "aprender-con-claude",
  },
  {
    id: "novedad-ia",
    category: "Aprender",
    title: "¿Me sirve esta novedad?",
    when: "Cuando ves una herramienta o función nueva y no sabes si te sirve.",
    text: "Te paso esto sobre [novedad]: [enlace o texto]. Explícame en tres frases qué es, si me sirve para mi proyecto de [tu proyecto] y cómo lo probaría sin romper nada.",
    guide: "mantente-al-dia",
  },
  {
    id: "explicame-facil",
    category: "Aprender",
    title: "Explícamelo fácil",
    when: "Cuando una palabra o un concepto se te atraganta.",
    text: "Explícame [concepto] como si tuviera doce años, con un ejemplo de la vida diaria. Después hazme una pregunta para comprobar que lo he entendido.",
    guide: "aprender-con-claude",
  },
  {
    id: "ponme-a-prueba",
    category: "Aprender",
    title: "Ponme a prueba",
    when: "Al terminar una sesión, para fijar lo aprendido.",
    text: "Hazme cinco preguntas tipo test sobre lo que hemos visto hoy. Espera mi respuesta a cada una antes de pasar a la siguiente y, al final, dime qué debería repasar.",
    guide: "aprender-con-claude",
  },
  {
    id: "resumen-apuntes",
    category: "Aprender",
    title: "Mis apuntes de hoy",
    when: "Antes de cerrar una sesión de aprendizaje.",
    text: "Resume lo que he aprendido hoy en cinco puntos sencillos, con un ejemplo de cada uno, para guardarlo en mis apuntes.",
    guide: "aprender-con-claude",
  },
  {
    id: "ordenar-carpetas",
    category: "Trabajar mejor",
    title: "Ordenar tu carpeta",
    when: "Cuando tu carpeta de proyecto se ha convertido en un cajón desastre.",
    text: "Revisa esta carpeta y propón una estructura ordenada. Explícame qué va en cada sitio y qué moverías, y espera a que te diga que sí antes de mover nada.",
    guide: "orden-de-carpetas",
  },
  {
    id: "usar-skill",
    category: "Trabajar mejor",
    title: "Usar una skill",
    when: "Cuando has instalado una skill y quieres asegurarte de que la usa.",
    text: "Tengo instalada la skill de [nombre]. Úsala para [tarea] y dime en qué parte del proceso la has aplicado.",
    guide: "skills",
  },
  {
    id: "cambiar-sesion",
    category: "Trabajar mejor",
    title: "Cambiar de sesión sin perder nada",
    when: "Antes de cerrar una conversación larga, para retomarla en otra.",
    text: "Antes de cerrar, crea un archivo CONTEXTO.md con: qué hemos hecho, las decisiones que tomamos y por qué, qué queda pendiente y cualquier aviso importante para la próxima sesión.",
    guide: "truquillos",
  },
  {
    id: "plan-antes",
    category: "Trabajar mejor",
    title: "Pide un plan antes del código",
    when: "Al empezar cualquier tarea que no sea trivial.",
    text: "Antes de escribir nada, explícame cómo lo harías por pasos y espera a que te diga que sí.",
    guide: "truquillos",
  },
  {
    id: "crear-claude-md",
    category: "Trabajar mejor",
    title: "Crea la memoria del proyecto",
    when: "Al empezar un proyecto, para no repetir lo mismo en cada sesión.",
    text: "Crea un archivo CLAUDE.md con lo esencial de este proyecto: qué es y para quién, tecnologías, estilo visual (colores, tipografías, tono), estructura de carpetas y lo que no debes tocar nunca. Que sea breve: máximo 40 líneas.",
    guide: "claude-code-primer-dia",
  },
  {
    id: "detector-vendehumos",
    category: "Contenido y redes",
    title: "¿Es un vendehumos?",
    when: "Antes de pagar un curso o seguir a alguien que promete demasiado.",
    text: "Te paso la descripción de este perfil o anuncio: [pega aquí el texto]. ¿Qué señales de alarma ves? ¿Qué le preguntarías antes de pagarle?",
    guide: "mantente-al-dia",
  },
  {
    id: "estrategia-contenidos",
    category: "Contenido y redes",
    title: "Estrategia de contenidos de 30 días",
    when: "Para planificar un mes de redes sin improvisar cada día.",
    text: "Quiero una estrategia de contenidos para los próximos 30 días. Antes de empezar, hazme las preguntas que necesites (máximo 5).\n\nQuién soy: [a qué te dedicas y qué te diferencia].\nQué tengo ya: [web, recursos, contenidos hechos].\nObjetivo: [por ejemplo, 5 clientes nuevos este mes].\nLímites: [horas a la semana] y canales [Instagram, LinkedIn…]. Nada de promesas exageradas ni urgencia falsa.\n\nEntrégame en tablas: tres pilares de contenido, un calendario de 4 semanas con día, formato, gancho y llamada a la acción, cinco fórmulas de gancho con ejemplo y qué métricas mirar cada semana.",
  },
  {
    id: "ganchos",
    category: "Contenido y redes",
    title: "Ganchos para un reel",
    when: "Cuando tienes el tema pero no sabes cómo empezar el vídeo.",
    text: "Dame 10 ganchos de menos de 10 palabras para un reel sobre [tema], dirigido a [público]. Que despierten curiosidad, pero sin clickbait ni promesas exageradas.",
  },
  {
    id: "guion-reel",
    category: "Contenido y redes",
    title: "Guion de un reel",
    when: "Para convertir una idea en un vídeo corto.",
    text: "Escribe el guion de un reel de 20 segundos sobre [tema]: un gancho en los 2 primeros segundos, tres ideas clave en frases muy cortas y un cierre que invite a [tu llamada a la acción]. Tono [cercano, divertido…]. Indica qué texto va en pantalla en cada momento.",
  },
];

export const getPrompt = (id: string) => prompts.find((p) => p.id === id);
